import type { Metadata } from "next";
import { PageHero, ContentSection, Prose } from "@/components/marketing/page-hero";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "How Tellequant collects, uses, and protects personal data.",
};

export default function PrivacyPage() {
  return (
    <>
      <PageHero
        eyebrow="Legal"
        title="Privacy Policy"
        subtitle="Last updated: 2026-04-18"
      />
      <ContentSection>
        <Prose>
          <p>
            This Privacy Policy explains how Tellequant, Inc. ("Tellequant," "we," "us") collects,
            uses, stores, and shares information when you use our platform (the "Service"). We
            take privacy seriously. The short version: we collect only what we need to operate the
            Service, never sell personal data, and never use your calls, transcripts, or knowledge
            base content to train AI models.
          </p>

          <h2>1. Information we collect</h2>
          <h3>Information you provide</h3>
          <ul>
            <li>Account data: name, email, workspace name, billing details.</li>
            <li>Configuration: agent personas, voices, tools, knowledge base documents.</li>
            <li>Contact lists you upload for outbound campaigns.</li>
          </ul>
          <h3>Information generated by use</h3>
          <ul>
            <li>Call metadata: timestamps, duration, participant numbers, agent used.</li>
            <li>Call recordings and transcripts, where enabled.</li>
            <li>System logs, usage metrics, and billing events.</li>
          </ul>
          <h3>Information from third parties</h3>
          <p>
            If you sign in with an identity provider (e.g., Google), we receive your name, email,
            and profile picture. Telephony partners (e.g., Twilio) deliver caller ID and media.
          </p>

          <h2>2. How we use it</h2>
          <ul>
            <li>To run the Service: provisioning numbers, routing calls, storing transcripts.</li>
            <li>To bill you accurately and prevent abuse.</li>
            <li>To improve reliability and detect incidents.</li>
            <li>To provide support when you ask for it.</li>
          </ul>
          <p>
            We do <strong>not</strong> use your content to train machine-learning models — ours or
            any vendor's. Our model-provider contracts explicitly exclude training on your data.
          </p>

          <h2>3. Sharing</h2>
          <p>
            We share data only with sub-processors required to deliver the Service (listed on our{" "}
            <a href="/security">Security page</a>), with your consent, or where required by law. We
            never sell personal information.
          </p>

          <h2>4. Retention</h2>
          <p>
            Default retention is 30 days for recordings and 2 years for transcripts, configurable
            per workspace. Deleting data from the dashboard purges it from backups within 30 days.
            Detailed retention terms live on the <a href="/security">Security page</a>.
          </p>

          <h2>5. Your rights</h2>
          <p>
            Depending on your location, you may have rights to access, correct, export, or delete
            your personal data, and to object to or restrict processing. Email{" "}
            <a href="mailto:privacy@tellequant.com">privacy@tellequant.com</a> to exercise these
            rights. We will respond within 30 days.
          </p>

          <h2>6. International transfers</h2>
          <p>
            Tellequant is operated from the United States with optional EU hosting. Where data
            leaves the EEA, we rely on Standard Contractual Clauses. Customers can elect EU-only
            residency in the dashboard.
          </p>

          <h2>7. Security</h2>
          <p>
            We encrypt data in transit (TLS 1.3) and at rest (AES-256), enforce row-level
            isolation in Postgres, and sign all inter-service calls. See the full posture on our{" "}
            <a href="/security">Security page</a>.
          </p>

          <h2>8. Children</h2>
          <p>
            The Service is not directed to children under 16. We do not knowingly collect personal
            data from children.
          </p>

          <h2>9. Changes</h2>
          <p>
            Material changes will be announced at least 30 days before taking effect. We'll email
            workspace owners and post the new policy with an updated date.
          </p>

          <h2>10. Contact</h2>
          <p>
            Questions? Email{" "}
            <a href="mailto:privacy@tellequant.com">privacy@tellequant.com</a>. For an EU/UK
            representative, write to <a href="mailto:dpo@tellequant.com">dpo@tellequant.com</a>.
          </p>
        </Prose>
      </ContentSection>
    </>
  );
}
